### ISSUE TITLE
CharacterTextSplitter

### ISSUE THREAD

**Issue by HavenDV** [tryAGI/LangChain#12]
- You can omit the base class implementation. Just one file where this works is enough, we'll highlight the interfaces a bit later.
- You can use GPT-4 for initial implementation
- Tests are encouraged but not required. It's better to do something minimal than nothing.

References:
- https://api.python.langchain.com/en/latest/text_splitter/langchain.text_splitter.CharacterTextSplitter.html

**Comment by TesAnti** [comment]
Working on this.
I want to use this example for tests: https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/character_text_splitter

But it requires "state_of_the_union.txt" as a bit piece of text to work with. May i add this file to repository directly or i should download and cache it during test execution?

**Comment by HavenDV** [comment]
You can add this file directly. Check LangChain.Splitters.CSharp.UnitTests to see how to add and use it quickly.
