### ISSUE TITLE
LLMChain ApplyAsync returning Task as result object, instead of text value

### ISSUE THREAD

**Issue by ericgreenmix** [tryAGI/LangChain#135]
### Describe the bug

Await of ParseResult was missed

### Steps to reproduce the bug

MapReduceDocumentsChain gave incorrect outputs

### Expected behavior

PR Incoming

**Comment by HavenDV** [comment]
Thank you very much for your contribution. Please write me your name in discord if you want and I will add you to the list of contrubutors and dev channel discussing development and immediate plans

**Comment by HavenDV** [comment]
<img width="716" alt="image" src="https://github.com/tryAGI/LangChain/assets/3002068/87c8babc-56cb-4c3c-919b-23a9f693767c">

We currently have two LLMChain implementations in the project and I’m not sure if this one is used. It wasn't added by me and I didn't pay much attention to it. And it seems we just need to compare these implementations and combine them correctly
I created issue according this: https://github.com/tryAGI/LangChain/issues/128
Initial info about this:
<img width="952" alt="image" src="https://github.com/tryAGI/LangChain/assets/3002068/9ae362ce-9665-4c6d-9824-8312f1958458">
