### ISSUE TITLE
AnalyzeDocumentChain

### ISSUE THREAD

**Issue by HavenDV** [tryAGI/LangChain#14]
- You can omit the base class implementation. Just one file where this works is enough, we'll highlight the interfaces a bit later.
- You can use GPT-4 for initial implementation
- Tests are encouraged but not required. It's better to do something minimal than nothing.

References:
- https://api.python.langchain.com/en/latest/chains/langchain.chains.combine_documents.base.AnalyzeDocumentChain.html

**Comment by khoroshevj** [comment]
missed this one, was done in https://github.com/tryAGI/LangChain/pull/43/files

**Comment by khoroshevj** [comment]
missed this one, was done in https://github.com/tryAGI/LangChain/pull/43/files
