### ISSUE TITLE
Concept: CLI Console tool to do some tasks

### ISSUE THREAD

**Issue by HavenDV** [tryAGI/LangChain#214]
For example, we have a list of commits/PRs with changes, and this is quite unreadable in the current version.
We can make NuGet with a console utility that will help you use our library for such tasks

Usage will be like this:
```
dotnet tool install -g langchain.cli
langchain auth openai OPENAI_API_KEY
langchain summarize --input CHANGES.md --output RELEASE-NOTES.md
```

Right now I mostly see use of this inside CICD

**Comment by curlyfro** [comment]
this is awesome!
