### ISSUE TITLE
Which endpoint should I fill in to use Azure Open AI?

### ISSUE THREAD

**Issue by qq312888991** [tryAGI/LangChain#24]
The code is as follows
```
const string apiKey = "xxxxx";
const string endpoint = "https://{resources_name}.openai.azure.com/openai/deployments/{deployment_name}/chat/completions?api-version=2023-07-01-preview";
using var httpClient = new HttpClient();
var model = new Gpt35TurboModel(apiKey, endpoint, httpClient);
var response = await model.GenerateAsync("你好");
Console.WriteLine(response);
```
![image](https://github.com/tryAGI/LangChain/assets/4046072/a2a59a7c-908c-489d-b68e-9ca501db1cf4)

**Comment by HavenDV** [comment]
Hi. Try to use `"https://{resources_name}.openai.azure.com/openai/deployments/{deployment_name}` as endpoint.

**Comment by qq312888991** [comment]
> Hi. Try to use `"https://{resources_name}.openai.azure.com/openai/deployments/{deployment_name}` as endpoint.

I've tried before, but I can't either
![image](https://github.com/tryAGI/LangChain/assets/4046072/3e4830f0-ce5c-4854-b812-3b615e81b898)

**Comment by qq312888991** [comment]
I have tested using HttpClient and this endpoint can be accessed normally

![image](https://github.com/tryAGI/LangChain/assets/4046072/c603a8bd-ebfd-49c9-9f54-d1a267d1bd18)

**Comment by HavenDV** [comment]
Thank you. Unfortunately, I don’t have the opportunity to test this within Azure, so I’m leaving the bug open for now. I will be happy to accept PR - we need to use the official Azure.AI.OpenAI package inside Langchain.Providers.Azure and provide the correct implementation.

**Comment by kharedev247** [comment]
Hi @HavenDV ,

I'll like to take it up and start working on it. I see in [OpenAiClientSettings ](https://github.com/tryAGI/OpenAI/blob/43baf2c816b337ccd6e44d7f4ca42456cddda024/src/libs/OpenAI/Client/Authentication/OpenAIClientSettings.cs#L76C1-L76C9), AzureOpenAI domain logic is already present.

So, I feel extending OpenAI Provider to work with Azure Open AI would be a good approach. (The other way I see is using [Azure.OpenAI Client Library](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ai.openai-readme?view=azure-dotnet-preview) which is yet in Preview)

Let me know your thoughts.

**Comment by HavenDV** [comment]
Thank you very much for your interest in this, we would appreciate any help.
I would prefer to use the official Microsoft library, even though it's in preview.
I'm also not sure if Azure servers support the same set of endpoints as OpenAI, so it will have a different set of implemented interfaces

**Comment by kharedev247** [comment]
Yeah, sounds more reliable. Will continue with Azure.OpenAI Client Library.

**Comment by kharedev247** [comment]
Hi @HavenDV , I think we are good to close this now !
