### ISSUE TITLE
Can LangChain in C# work with a a local LLM model

### ISSUE THREAD

**Issue by starchou6** [tryAGI/LangChain#30]
## What would you like to be added:
LangChain in C# work with a local LLM model
## Why is this needed:
I had a local LLM model service, I want to use it instead of the OpenAI's service.I think this is a common function.
## Anything else we need to know?
It is very easy in Python.
`import os
import openai
openai.api_base = "http://localhost:8080/v1"
openai.api_key = "sx-xxx"
OPENAI_API_KEY = "sx-xxx"
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

completion = openai.ChatCompletion.create(
  model="lunademo",
  messages=[
    {"role": "system", "content": "You are a math teacher"},
    {"role": "user", "content": "What is Pi"}
  ]
)`

**Comment by chuongmep** [comment]
That will be a good thing if we have !

**Comment by HavenDV** [comment]
I'm not sure, but try this:
```csharp
using var client = new HttpClient();
var model = new OpenAiModel(apiKey, client, "lunademo");
model.Api.BaseUrl = "http://localhost:8080/v1";
```
or
```csharp
var configuration = new OpenAiConfiguration
{
    ApiKey = "",
    Endpoint = "http://localhost:8080/v1",
    ModelId = "lunademo",
}
var model = new OpenAiModel(configuration, client);
```

**Comment by starchou6** [comment]
> I'm not sure, but try this:
> 
> ```cs
> using var client = new HttpClient();
> var model = new OpenAiModel(apiKey, client, "lunademo");
> model.Api.BaseUrl = "http://localhost:8080/v1";
> ```
> 
> or
> 
> ```cs
> var configuration = new OpenAiConfiguration
> {
>     ApiKey = "",
>     Endpoint = "http://localhost:8080/v1",
>     ModelId = "lunademo",
> }
> var model = new OpenAiModel(configuration, client);
> ```

Thanks for your reply.
I tried above 2 ways and both got error "Model name lunademo is not supported.".

**Comment by HavenDV** [comment]
I released fix for this yesterday, please check

**Comment by ChengYen-Tang** [comment]
Hello everyone,
I have an idea.
We can try to integrate [LLamaSharp](https://github.com/SciSharp/LLamaSharp) project.

**Comment by HavenDV** [comment]
> Hello everyone, I have an idea. We can try to integrate [LLamaSharp](https://github.com/SciSharp/LLamaSharp) project.

Cool idea! added as a separate issue - https://github.com/tryAGI/LangChain/issues/32. Of course, I’ll be happy to accept PR, because I can’t handle everything alone, but if not, I’ll do it in my free time
