### ISSUE TITLE
Integrate LLamaSharp project

### ISSUE THREAD

**Issue by HavenDV** [tryAGI/LangChain#32]
https://github.com/SciSharp/LLamaSharp

You need to create a separate LangChain.Providers.LLamaSharp provider and add a minimal implementation of things from LangChain.Providers.Abstractions.

**Comment by TesAnti** [comment]
accordind to their github, as llama progresses it looses compatibility with old models.
i was able to run v0.3.0 together with matching model. The latest version is 0.7.0(which has different API) but there is no clear instructions on how to run it.
Also there is different backends avaliable(CPU, Cuda, Mac)

What i suggest is to implement v0.3.0 without any backend included. Then user would have to add a reference to required backend during usage. In this was we would have something working.

**Comment by HavenDV** [comment]
I haven't used it, so if you think so and want to do it, then that's ok for me.
Now we are better off having something than having nothing. We may fix this in the future if necessary.

**Comment by ChengYen-Tang** [comment]
Hi @TesAnti ,

I have some suggestions and requests.
1. 0.7.0 model conversion method: https://github.com/ggerganov/llama.cpp#prepare-data--run or https://github.com/SciSharp/LLamaSharp/blob/master/docs/LLamaModel/quantization.md
2. Embeddings: https://github.com/SciSharp/LLamaSharp/blob/master/docs/LLamaModel/embeddings.md
3. Tokenization: https://github.com/SciSharp/LLamaSharp/blob/master/docs/LLamaModel/tokenization.md
