### ISSUE TITLE
LLamaSharpEmbeddings Exception: EmbeddingMode must be true.

### ISSUE THREAD

**Issue by SrNandu** [tryAGI/LangChain#343]
### Describe the bug

When creating a LlamaSharpEmbeddings the LlamaEmbedder expects the property EmbeddingMode to be true, even if i set it to true in the LlamaSharpConfiguration it is not beign passed to the model params.
![image](https://github.com/tryAGI/LangChain/assets/30204958/6528819d-7ec5-42de-b73c-9473b94a092c)
![image](https://github.com/tryAGI/LangChain/assets/30204958/d98d717c-b779-43e7-8bb1-1ffd951acf5a)
This is the LlamaSharp code that throws the exception:
![image](https://github.com/tryAGI/LangChain/assets/30204958/ac4b8948-9f76-4067-a444-c8487932d58e)

### Steps to reproduce the bug

1. Create a LLamaSharpEmbeddings

### Expected behavior

Adding this line of code should fix the problem:
![image](https://github.com/tryAGI/LangChain/assets/30204958/f9ea3ca3-30d1-4923-a1ed-19b8f168c951)

**Comment by HavenDV** [comment]
Hello.
Thanks, I think this problem is due to the fact that the LLamaSharp provider was originally written for version 0.8, but after that it was incorrectly updated to new versions
I'll be happy to accept PR on this or take a look at it this weekend
