### ISSUE TITLE
CompletedResponseGenerated occurs twice 

### ISSUE THREAD

**Issue by PankajRawat333** [tryAGI/LangChain#375]
### Describe the bug

I want to perform some operations on the CompletedResponseGenerated events, but I noticed that this event occurs twice. When I was examining the source code, I couldn't understand why the OnCompletedResponseGenerated method is being called twice. 

![image](https://github.com/tryAGI/LangChain/assets/21244341/fd658470-cf23-49b7-8547-04bfc7a36017)

Help me understand if this behavior is expected?

### Steps to reproduce the bug

```
static async Task Main(string[] args)
{
    Console.WriteLine("Welcome to LangChain .NET");
    var provider = new BedrockProvider(RegionEndpoint.USEast1);
    var llm = new Claude3SonnetModel(provider)
    {
        Settings = new BedrockChatSettings
        {
            UseStreaming = true
        }
    };

    llm.PromptSent += (_, prompt) => Console.WriteLine($"Prompt: {prompt}");
    llm.PartialResponseGenerated += (_, delta) => Console.Write(delta);
    llm.CompletedResponseGenerated += (_, prompt) => Console.WriteLine($"Completed response: {prompt}");

    var prompt = @"
    Who was the President of the United States in the year 2000? Just give me answer, no explaination";

    var response = await llm.GenerateAsync(prompt);

    Console.Read();
}
```

### Screenshots

![image](https://github.com/tryAGI/LangChain/assets/21244341/0922e651-9c10-40ff-a414-abaa14b04950)

### NuGet package version

0.15.0

**Comment by HavenDV** [comment]
Thank you, this is indeed a mistake.
Fixed in latest preview.
