### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by mweel1** [tryAGI/LangChain#404]
### Describe the bug

I copied the example and these methods are not found

<img width="890" alt="image" src="https://github.com/user-attachments/assets/2b35caf5-b66b-48f6-b899-74e6393598ea">

### Steps to reproduce the bug

Download the dependencies (not prerelease)
Copy example code from Github home page
Compile

### Expected behavior

Expect function to be found

### NuGet package version

15.0

**Comment by curlyfro** [comment]
add
`using static LangChain.Chains.Chain;
`

**Comment by mweel1** [comment]
@curlyfro that did the trick, thanks!
