### ISSUE TITLE
Wiki isn't working

### ISSUE THREAD

**Issue by wr-dev** [tryAGI/LangChain#455]
### Describe the bug

https://github.com/tryAGI/LangChain/wiki/

When attempting to view the wiki, only one page is available: [Checking internet speed with Crew and Ollama](https://github.com/tryAGI/LangChain/wiki/Checking-internet-speed-with-Crew-and-Ollama)

### Steps to reproduce the bug

1. Go to https://github.com/tryAGI/LangChain/wiki/
2. Click on any article

### Expected behavior

Should be able to see the article

**Comment by HavenDV** [comment]
The current updated documentation is here: https://tryagi.github.io/LangChain/

Need to move the remaining two articles from the old wiki and delete it
