### ISSUE TITLE
SQLDatabaseChain

### ISSUE THREAD

**Issue by HavenDV** [tryAGI/LangChain#73]
- You can omit the base class implementation. Just one file where this works is enough, we'll highlight the interfaces a bit later.
- You can use GPT-4 for initial implementation
- Tests are encouraged but not required. It's better to do something minimal than nothing.

References:
- https://api.python.langchain.com/en/latest/sql/langchain_experimental.sql.base.SQLDatabaseChain.html

**Comment by mystery000** [comment]
Thank you very much!

**Comment by khoroshevj** [comment]
@HavenDV I guess we can close this one?

**Comment by HavenDV** [comment]
Yes, but also feel free to close it yourself, I think you have sufficient rights
